import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import pg from 'pg';
import { randomUUID } from 'node:crypto';

test('Payment database lifecycle, concurrent delivery and durable send outcomes', { skip: !process.env.TEST_DATABASE_URL }, async t => {
  const url = new URL(process.env.TEST_DATABASE_URL);
  if (!url.pathname.endsWith('_regression') || !['127.0.0.1','localhost'].includes(url.hostname)) throw Error('Isolated regression database required');
  const schema = 'payment_test_'+randomUUID().replaceAll('-', '');
  const admin = new pg.Pool({connectionString: url.href});
  await admin.query(`CREATE SCHEMA ${schema}`);
  Object.assign(process.env, {DB_HOST:url.hostname,DB_PORT:url.port,DB_NAME:url.pathname.slice(1),DB_USER:decodeURIComponent(url.username),DB_PASSWORD:decodeURIComponent(url.password)});
  const {default: pool} = await import('../db.js');
  pool.options.options = `-c search_path=${schema}`;
  t.after(async () => { await pool.end(); await admin.query(`DROP SCHEMA ${schema} CASCADE`); await admin.end(); });
  await pool.query(`CREATE TABLE providers (provider_id UUID PRIMARY KEY, provider_name TEXT,nphies_id TEXT,provider_type TEXT);
    CREATE TABLE insurers (insurer_id UUID PRIMARY KEY,insurer_name TEXT,nphies_id TEXT);
    CREATE TABLE claim_submissions (id SERIAL PRIMARY KEY,claim_number TEXT,status TEXT,request_bundle JSONB);`);
  for (const file of ['029_payment_reconciliation.sql','030_payment_notice_columns.sql','065_payment_notice_attempts.sql','065_payment_notice_attempts.sql']) {
    await pool.query(await fs.readFile(new URL('../migrations/'+file, import.meta.url),'utf8'));
  }
  await pool.query('INSERT INTO providers VALUES ($1,$2,$3,$4)',[randomUUID(),'Synthetic provider','DC-FHIR','5']);
  await pool.query('INSERT INTO insurers VALUES ($1,$2,$3)',[randomUUID(),'Synthetic payer','INS-FHIR']);
  const {default: service} = await import('../services/paymentReconciliationService.js');
  const {default: transport} = await import('../services/nphiesService.js');
  const bundle = JSON.parse(await fs.readFile(new URL('./fixtures/payment-reconciliation-official.json',import.meta.url)));
  const pr = bundle.entry[1].resource;
  pr.detail[0].identifier = {system:'https://test/detail',value:'detail-1'};
  pr.detail[0].predecessor = {system:'https://test/detail',value:'detail-0'};
  // Unknown extension values are retained independently.
  for (const name of ['a','b']) pr.detail[0].extension.push({url:'https://test/'+name,valueMoney:{value:1,currency:'SAR'}});
  const results = await Promise.all([service.processBundle(bundle), service.processBundle(bundle)]);
  assert.ok(results.every(r => r.success));
  assert.equal(results.filter(r => r.duplicate).length,1);
  assert.equal((await pool.query('SELECT count(*) FROM payment_reconciliations')).rows[0].count,'1');
  const id = results[0].reconciliationId;
  const record = await service.getById(id);
  assert.equal(record.provider_nphies_id,'DC-FHIR');
  assert.equal(record.details[0].predecessor_identifier.value,'detail-0');
  assert.equal(record.details[0].components.length,5);
  assert.equal(record.response_bundle.entry[0].resource.response.code,'ok');
  assert.equal(record.response_bundle.entry[0].resource.destination[0].receiver.identifier.value,'INS-FHIR');
  assert.equal(record.response_bundle.entry[0].resource.sender.identifier.value,'DC-FHIR');
  const receipt = {bankReceiptConfirmed:true,receivedDate:'2026-01-01',receiptReference:'SYNTHETIC-RECEIPT'};
  await assert.rejects(service.sendPaymentNotice(id,'paid',{}),/Confirm actual bank receipt/);
  const send = t.mock.method(transport,'sendPaymentNotice',async request => ({success:true,deliveryState:'accepted',status:200,data:{resourceType:'Bundle'},nphiesErrors:[]}));
  const concurrent = await Promise.allSettled([service.sendPaymentNotice(id,'paid',receipt),service.sendPaymentNotice(id,'paid',receipt)]);
  assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(send.mock.callCount(),1);
  await assert.rejects(service.sendPaymentNotice(id,'paid',receipt),/already been sent/);
  send.mock.restore();
  const timeout = t.mock.method(transport,'sendPaymentNotice',async () => ({success:false,deliveryState:'unknown',error:'timeout'}));
  assert.equal((await service.sendPaymentNotice(id,'cleared',receipt)).deliveryState,'unknown');
  await assert.rejects(service.sendPaymentNotice(id,'cleared',receipt),/uncertain/);
  assert.equal(timeout.mock.callCount(),1);
  const attempts = (await service.getById(id)).notice_attempts;
  assert.deepEqual(attempts.map(a=>a.status),['unknown','accepted']);
  assert.equal((await service.getById(id)).payment_status_sent,'paid');
  await pool.query('CREATE TABLE payments (payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),payment_ref TEXT UNIQUE,amount NUMERIC,payment_date DATE,status TEXT,provider_id UUID,insurer_id UUID)');
  const providerId = (await pool.query('SELECT provider_id FROM providers')).rows[0].provider_id;
  const insurerId = (await pool.query('SELECT insurer_id FROM insurers')).rows[0].insurer_id;
  const {default:payments} = await import('../controllers/paymentsController.js');
  const res = () => ({statusCode:200,status(code){this.statusCode=code;return this;},json(data){this.body=data;return this;}});
  const created=res();
  await payments.create({body:{payment_ref_number:'SYNTHETIC-LOCAL',total_amount:10,provider_id:providerId,insurer_id:insurerId,payment_date:'2026-01-01',status:'paid'}},created);
  assert.equal(created.statusCode,201);
  assert.equal(created.body.data.payment_ref,'SYNTHETIC-LOCAL');
  const updated=res();
  await payments.updatePayment({params:{id:created.body.data.payment_id},body:{total_paid_amount:0}},updated);
  assert.equal(updated.statusCode,200);
  assert.equal(Number(updated.body.data.amount),0);
  const invalid=res();
  await payments.updatePayment({params:{id:created.body.data.payment_id},body:{total_paid_amount:-1}},invalid);
  assert.equal(invalid.statusCode,400);
});
