-- Migration 049: intentionally a no-op.
--
-- This file used to insert a fixed administrator email with a committed bcrypt
-- hash and reset that account's password on every run. Those credentials are
-- public and must be treated as compromised; rotate them in any database where
-- this migration ran.
--
-- Create or promote administrators explicitly instead:
--   ADMIN_PASSWORD='<strong password>' node scripts/createAdminUser.js <email>
--   npm run grant-admin -- <existing-user-email>
SELECT 1;
