-- Migration: Add comprehensive NPHIES response data storage
-- Date: 2025-11-26
-- Description: Adds columns and tables for storing full NPHIES eligibility response data
-- Reference: https://portal.nphies.sa/ig/usecase-eligibility.html

-- ==========================================
-- ELIGIBILITY TABLE ADDITIONS
-- ==========================================

-- Add disposition field from CoverageEligibilityResponse
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS disposition TEXT;

-- Add response code from MessageHeader.response.code
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS response_code VARCHAR(50);

-- Flag to indicate if response was generated by NPHIES (timeout scenario)
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS is_nphies_generated BOOLEAN DEFAULT FALSE;

-- Add serviced period fields
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS serviced_period_start DATE;
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS serviced_period_end DATE;

-- Add timestamps for request/response
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add indexes for new columns
CREATE INDEX IF NOT EXISTS idx_eligibility_response_code ON eligibility(response_code);
CREATE INDEX IF NOT EXISTS idx_eligibility_is_nphies_generated ON eligibility(is_nphies_generated);
CREATE INDEX IF NOT EXISTS idx_eligibility_created_at ON eligibility(created_at);

-- Add column comments
COMMENT ON COLUMN eligibility.disposition IS 'Human-readable disposition text from NPHIES response';
COMMENT ON COLUMN eligibility.response_code IS 'Response code from NPHIES MessageHeader';
COMMENT ON COLUMN eligibility.is_nphies_generated IS 'True if response was generated by NPHIES (timeout/error scenario)';

-- ==========================================
-- PATIENT_COVERAGE TABLE ADDITIONS
-- ==========================================

-- Add NPHIES-specific coverage ID
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS nphies_coverage_id VARCHAR(100);

-- Add subscriber ID (can differ from member_id in some cases)
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS subscriber_id VARCHAR(100);

-- Add dependent number
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS dependent VARCHAR(10);

-- Add coverage class information from NPHIES
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS class_code VARCHAR(50);
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS class_name VARCHAR(255);

-- Add network information
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS network VARCHAR(100);

-- Add period fields (if not already present)
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS period_start DATE;
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS period_end DATE;

-- Add timestamps
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Create indexes for coverage lookup
CREATE INDEX IF NOT EXISTS idx_patient_coverage_nphies_id ON patient_coverage(nphies_coverage_id);
CREATE INDEX IF NOT EXISTS idx_patient_coverage_subscriber_id ON patient_coverage(subscriber_id);
CREATE INDEX IF NOT EXISTS idx_patient_coverage_network ON patient_coverage(network);

-- Add column comments
COMMENT ON COLUMN patient_coverage.nphies_coverage_id IS 'NPHIES internal coverage identifier';
COMMENT ON COLUMN patient_coverage.subscriber_id IS 'Insurance subscriber ID from NPHIES';
COMMENT ON COLUMN patient_coverage.dependent IS 'Dependent number for family coverage';
COMMENT ON COLUMN patient_coverage.class_code IS 'Coverage class code (e.g., plan code)';
COMMENT ON COLUMN patient_coverage.class_name IS 'Coverage class name (e.g., plan name)';
COMMENT ON COLUMN patient_coverage.network IS 'Coverage network type (in-network, out-of-network)';

-- ==========================================
-- PATIENTS TABLE ADDITIONS
-- ==========================================

-- Add NPHIES patient ID for cross-reference
ALTER TABLE patients ADD COLUMN IF NOT EXISTS nphies_patient_id VARCHAR(100);

-- Add identifier system (e.g., http://nphies.sa/identifier/iqama)
ALTER TABLE patients ADD COLUMN IF NOT EXISTS identifier_system VARCHAR(255);

-- Add telecom JSONB for multiple contact methods
ALTER TABLE patients ADD COLUMN IF NOT EXISTS telecom JSONB;

-- Add structured address
ALTER TABLE patients ADD COLUMN IF NOT EXISTS address_details JSONB;

-- Add timestamps
ALTER TABLE patients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_patients_nphies_id ON patients(nphies_patient_id);
CREATE INDEX IF NOT EXISTS idx_patients_identifier_system ON patients(identifier_system);

-- Add column comments
COMMENT ON COLUMN patients.nphies_patient_id IS 'NPHIES internal patient identifier';
COMMENT ON COLUMN patients.identifier_system IS 'Identifier system URI from NPHIES';
COMMENT ON COLUMN patients.telecom IS 'JSON array of contact methods (phone, email, etc.)';
COMMENT ON COLUMN patients.address_details IS 'JSON structured address from NPHIES';

-- ==========================================
-- ELIGIBILITY_BENEFITS TABLE (NEW)
-- ==========================================

-- Create table for detailed benefit storage from NPHIES response
CREATE TABLE IF NOT EXISTS eligibility_benefits (
  benefit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  eligibility_id UUID REFERENCES eligibility(eligibility_id) ON DELETE CASCADE,
  
  -- Benefit category (e.g., medical-care, dental, vision)
  category VARCHAR(100),
  
  -- Network type (in, out)
  network VARCHAR(50),
  
  -- Unit type (individual, family)
  unit VARCHAR(50),
  
  -- Term (annual, lifetime)
  term VARCHAR(50),
  
  -- Benefit type (benefit, copay, deductible, coinsurance)
  benefit_type VARCHAR(100),
  
  -- Allowed amount
  allowed_value DECIMAL(12,2),
  allowed_currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Used amount
  used_value DECIMAL(12,2),
  used_currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Exclusion flag
  excluded BOOLEAN DEFAULT FALSE,
  
  -- Benefit name and description
  name VARCHAR(255),
  description TEXT,
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for benefits
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_eligibility_id ON eligibility_benefits(eligibility_id);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_category ON eligibility_benefits(category);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_network ON eligibility_benefits(network);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_excluded ON eligibility_benefits(excluded);

-- Add table comment
COMMENT ON TABLE eligibility_benefits IS 'Stores detailed benefit information from NPHIES eligibility responses';

-- ==========================================
-- INSURERS TABLE ADDITIONS
-- ==========================================

-- Add updated_at timestamp if not exists
ALTER TABLE insurers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ==========================================
-- PROVIDERS TABLE ADDITIONS  
-- ==========================================

-- Add updated_at timestamp if not exists
ALTER TABLE providers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ==========================================
-- UTILITY FUNCTION: Update timestamp trigger
-- ==========================================

-- Create function to automatically update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for automatic updated_at
DO $$ 
BEGIN
  -- Patients trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_patients_updated_at') THEN
    CREATE TRIGGER update_patients_updated_at
      BEFORE UPDATE ON patients
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Patient_coverage trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_patient_coverage_updated_at') THEN
    CREATE TRIGGER update_patient_coverage_updated_at
      BEFORE UPDATE ON patient_coverage
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Insurers trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_insurers_updated_at') THEN
    CREATE TRIGGER update_insurers_updated_at
      BEFORE UPDATE ON insurers
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Providers trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_providers_updated_at') THEN
    CREATE TRIGGER update_providers_updated_at
      BEFORE UPDATE ON providers
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

