-- Migration: Add Missing NPHIES Columns
-- Date: 2025-11-26
-- Description: Adds missing columns from the comprehensive NPHIES migration
-- Run this in pgAdmin Query Tool

-- ==========================================
-- ELIGIBILITY TABLE - MISSING COLUMNS
-- ==========================================

-- Add disposition field from CoverageEligibilityResponse
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS disposition TEXT;

-- Add response code from MessageHeader.response.code
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS response_code VARCHAR(50);

-- Flag to indicate if response was generated by NPHIES (timeout scenario)
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS is_nphies_generated BOOLEAN DEFAULT FALSE;

-- Add serviced period fields
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS serviced_period_start DATE;
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS serviced_period_end DATE;

-- Add created_at timestamp
ALTER TABLE eligibility ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add indexes for eligibility
CREATE INDEX IF NOT EXISTS idx_eligibility_response_code ON eligibility(response_code);
CREATE INDEX IF NOT EXISTS idx_eligibility_is_nphies_generated ON eligibility(is_nphies_generated);
CREATE INDEX IF NOT EXISTS idx_eligibility_created_at ON eligibility(created_at);
CREATE INDEX IF NOT EXISTS idx_eligibility_site_eligibility ON eligibility(site_eligibility);
CREATE INDEX IF NOT EXISTS idx_eligibility_is_transfer ON eligibility(is_transfer);

-- ==========================================
-- PATIENTS TABLE - MISSING COLUMNS
-- ==========================================

-- Add NPHIES patient ID for cross-reference
ALTER TABLE patients ADD COLUMN IF NOT EXISTS nphies_patient_id VARCHAR(100);

-- Add identifier system (e.g., http://nphies.sa/identifier/iqama)
ALTER TABLE patients ADD COLUMN IF NOT EXISTS identifier_system VARCHAR(255);

-- Add telecom JSONB for multiple contact methods
ALTER TABLE patients ADD COLUMN IF NOT EXISTS telecom JSONB;

-- Add structured address
ALTER TABLE patients ADD COLUMN IF NOT EXISTS address_details JSONB;

-- Create indexes for patients
CREATE INDEX IF NOT EXISTS idx_patients_nphies_id ON patients(nphies_patient_id);
CREATE INDEX IF NOT EXISTS idx_patients_identifier_system ON patients(identifier_system);
CREATE INDEX IF NOT EXISTS idx_patients_is_newborn ON patients(is_newborn);

-- ==========================================
-- PATIENT_COVERAGE TABLE - MISSING COLUMNS
-- ==========================================

-- Add NPHIES-specific coverage ID
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS nphies_coverage_id VARCHAR(100);

-- Add subscriber ID (can differ from member_id in some cases)
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS subscriber_id VARCHAR(100);

-- Add dependent number (short format)
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS dependent VARCHAR(10);

-- Add coverage class information from NPHIES
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS class_code VARCHAR(50);
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS class_name VARCHAR(255);

-- Add network information
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS network VARCHAR(100);

-- Add period fields
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS period_start DATE;
ALTER TABLE patient_coverage ADD COLUMN IF NOT EXISTS period_end DATE;

-- Create indexes for patient_coverage
CREATE INDEX IF NOT EXISTS idx_patient_coverage_nphies_id ON patient_coverage(nphies_coverage_id);
CREATE INDEX IF NOT EXISTS idx_patient_coverage_subscriber_id ON patient_coverage(subscriber_id);
CREATE INDEX IF NOT EXISTS idx_patient_coverage_network ON patient_coverage(network);

-- ==========================================
-- ELIGIBILITY_BENEFITS TABLE (NEW)
-- ==========================================

-- Create table for detailed benefit storage from NPHIES response
CREATE TABLE IF NOT EXISTS eligibility_benefits (
  benefit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  eligibility_id UUID REFERENCES eligibility(eligibility_id) ON DELETE CASCADE,
  
  -- Benefit category (e.g., medical-care, dental, vision)
  category VARCHAR(100),
  
  -- Network type (in, out)
  network VARCHAR(50),
  
  -- Unit type (individual, family)
  unit VARCHAR(50),
  
  -- Term (annual, lifetime)
  term VARCHAR(50),
  
  -- Benefit type (benefit, copay, deductible, coinsurance)
  benefit_type VARCHAR(100),
  
  -- Allowed amount
  allowed_value DECIMAL(12,2),
  allowed_currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Used amount
  used_value DECIMAL(12,2),
  used_currency VARCHAR(3) DEFAULT 'SAR',
  
  -- Exclusion flag
  excluded BOOLEAN DEFAULT FALSE,
  
  -- Benefit name and description
  name VARCHAR(255),
  description TEXT,
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for benefits
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_eligibility_id ON eligibility_benefits(eligibility_id);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_category ON eligibility_benefits(category);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_network ON eligibility_benefits(network);
CREATE INDEX IF NOT EXISTS idx_eligibility_benefits_excluded ON eligibility_benefits(excluded);

-- ==========================================
-- INSURERS TABLE - ADD TIMESTAMP
-- ==========================================

ALTER TABLE insurers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ==========================================
-- PROVIDERS TABLE - ADD TIMESTAMP
-- ==========================================

ALTER TABLE providers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ==========================================
-- UTILITY: Auto-update timestamp trigger
-- ==========================================

-- Create function to automatically update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for automatic updated_at (if they don't exist)
DO $$ 
BEGIN
  -- Patients trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_patients_updated_at') THEN
    CREATE TRIGGER update_patients_updated_at
      BEFORE UPDATE ON patients
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Patient_coverage trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_patient_coverage_updated_at') THEN
    CREATE TRIGGER update_patient_coverage_updated_at
      BEFORE UPDATE ON patient_coverage
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Insurers trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_insurers_updated_at') THEN
    CREATE TRIGGER update_insurers_updated_at
      BEFORE UPDATE ON insurers
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  
  -- Providers trigger
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_providers_updated_at') THEN
    CREATE TRIGGER update_providers_updated_at
      BEFORE UPDATE ON providers
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- ==========================================
-- VERIFICATION QUERY (run after migration)
-- ==========================================
-- SELECT 
--   'eligibility' as table_name, 
--   COUNT(*) as column_count 
-- FROM information_schema.columns 
-- WHERE table_name = 'eligibility'
-- UNION ALL
-- SELECT 
--   'patients', 
--   COUNT(*) 
-- FROM information_schema.columns 
-- WHERE table_name = 'patients'
-- UNION ALL
-- SELECT 
--   'patient_coverage', 
--   COUNT(*) 
-- FROM information_schema.columns 
-- WHERE table_name = 'patient_coverage'
-- UNION ALL
-- SELECT 
--   'eligibility_benefits', 
--   COUNT(*) 
-- FROM information_schema.columns 
-- WHERE table_name = 'eligibility_benefits';

