-- Fix embedding dimension mismatch for medicines: vector(768) -> vector(4096)
-- (cniongolo/biomistral produces 4096-dimension embeddings).
--
-- Idempotent and non-destructive: it only acts when the column is not already
-- vector(4096). Embeddings of another dimension cannot be cast, so they are set
-- to NULL (they are regenerated by the next medicine import); medicine, brand and
-- code rows are kept. This file used to TRUNCATE all three tables on every run.
--
-- No HNSW/ivfflat index is created: pgvector indexes support at most 2000
-- dimensions, so the previous CREATE INDEX always failed silently.

DO $$
DECLARE
    current_dim integer;
BEGIN
    SELECT a.atttypmod INTO current_dim
    FROM pg_attribute a
    WHERE a.attrelid = 'medicines'::regclass AND a.attname = 'embedding' AND NOT a.attisdropped;

    IF current_dim IS DISTINCT FROM 4096 THEN
        DROP INDEX IF EXISTS idx_medicines_embedding;
        UPDATE medicines SET embedding = NULL WHERE embedding IS NOT NULL;
        ALTER TABLE medicines ALTER COLUMN embedding TYPE vector(4096);
        RAISE NOTICE 'medicines.embedding changed to vector(4096); existing embeddings cleared';
    END IF;
END $$;

COMMENT ON COLUMN medicines.embedding IS 'Vector embedding (4096 dimensions) for RAG-based semantic search using cniongolo/biomistral model';
