/**
 * Standard envelope for every AI / advisory response (AI spec, principle 2):
 *   source     'rules' | 'statistics' | 'retrieval' | 'llm'
 *   certainty  'high' | 'medium' | 'low'
 *   basis      what data, rules or documents were used (with sample size when statistical)
 *   disclaimer present when the content is clinical
 * Unavailable AI is reported as { available: false, reason } (principle 3), never as "valid".
 */

export const AI_SOURCES = Object.freeze(['rules', 'statistics', 'retrieval', 'llm']);
export const CERTAINTIES = Object.freeze(['high', 'medium', 'low']);

export const CLINICAL_DISCLAIMER =
  'Advisory only. This is not a clinical or coverage decision; a qualified person must review it before acting.';
export const LLM_DISCLAIMER =
  'Generated by a language model from the data shown. It may be wrong; verify against the NPHIES error codes and profiles.';

export function envelope({ source, certainty, basis, disclaimer, ...data } = {}) {
  if (!AI_SOURCES.includes(source)) throw new Error(`Invalid AI response source: ${source}`);
  if (!CERTAINTIES.includes(certainty)) throw new Error(`Invalid AI response certainty: ${certainty}`);
  const emptyBasis = basis === undefined || basis === null || basis === '' ||
    (typeof basis === 'object' && Object.keys(basis).length === 0);
  if (emptyBasis) throw new Error('AI response basis is required');
  return { source, certainty, basis, ...(disclaimer ? { disclaimer } : {}), ...data };
}

export function unavailable(reason, extra = {}) {
  return { available: false, reason: String(reason || 'AI is unavailable'), ...extra };
}

export function insufficientData({ count, minimum, ...extra }) {
  return { insufficientData: true, count, minimum, ...extra };
}
